### ISSUE TITLE
Status?

### ISSUE THREAD

**Issue by jtagcat** [CodeRibbon/VSCodeRibbon#23]
Yesterday-today I tried switching to Atom. I can't make any use out of it.

 - Breaking blockers: it seems that Golang support is [abandoned](https://github.com/joefitzgerald/go-plus).
 - Weird keyboard shortcuts: I have to remap most of them to make them reachable.
 - Not used to it: besides the basics, navigating in a file is just difficult; stuff I expect, just isn't there, or I don't know of it.

I wanted to demo CodeRibbon, yet there is no practical way for me to do it. As such, I'm probing on the status of the ~~VSCode~~ VSCodium version: there has been 0 activity for almost a year.

**Comment by robobenklein** [comment]
Well "not good" is the shortest answer.

My research lab has been disbanded since both the professors left UTK. ( my prior advisor: https://austinhenley.com/blog/leavingacademia.html ) So I no longer have funding after this semester to continue a PhD, and I don't think any other professors at UTK are interested in picking up CodeRibbon. (Though WorldSyntaxTree has a non-zero chance) I am not even certain if I will complete a masters at this rate, so having enough income to live off of is my current priority.

This doesn't mean I've given up on it though, I started work on CodeRibbon before I was a grad student and will likely continue developing it afterwards. Right now I'm trying to get some additional hands on VSCR by means of a class project, but starting this semester with a covid infection isn't making it easier. While I'm stuck at home at least I can spend some more time writing code.

**Comment by robobenklein** [comment]
New status: moved to https://github.com/CodeRibbon/CodeRibbon-Theia and progress is looking good again. Nowhere near feature-complete or comparable yet, but minimal implementation proves the technology is working.
